### ISSUE TITLE
invalid format in printf

### ISSUE THREAD

**Issue by whydee86** [OWASP/D4N155#26]
There are some strings that break the printf command in read.sh file.
![image](https://user-images.githubusercontent.com/43274863/151478122-92b4eef9-3d19-478e-acf9-60fec59da509.png)
As a result of the following error, the wordlists file was not created.
![error](https://user-images.githubusercontent.com/43274863/151479070-299a5e57-6879-47ad-b6df-ec013e17bc2d.png)

**Comment by Jul10l1r4** [comment]
You can get stats of Memory and CPU running D4N155?

**Comment by whydee86** [comment]
This is good?
![WindowsTerminal_gsBrieLAuS](https://user-images.githubusercontent.com/43274863/151721397-cb7d9b16-b756-43f3-aa0f-775716278648.png)
As you can see above this is running on the right tab and on the left tab this is the TOP command

**Comment by Jul10l1r4** [comment]
apparently seems to have extrapolated memory limit
