### ISSUE TITLE
leet applied on all final content

### ISSUE THREAD

**Issue by fedeb95** [OWASP/D4N155#28]
hi, I've seen that leet is applied only to the upper case letters of the original list of words you supply with -b parameter. Shouldn't it leet all final combinations of words and add them to the final list, also exchanging lowercase letters with numbers? 

I can work of this if needed. Otherwise I'll just work on making further processing from the generated wordlist.

**Comment by Jul10l1r4** [comment]
lol, i dont see... U'll work it? thnx!

**Comment by fedeb95** [comment]
I mean, if it is a desired feature yes. A drawback could be generating too many entries

**Comment by Jul10l1r4** [comment]
Lowercase letters are being a problem. you can do it?

**Comment by fedeb95** [comment]
https://github.com/OWASP/D4N155/pull/30 this should leet lowercase letters too. How about optionally leeting all the final content? That is, if I have "leet" as the only line in my input file with -b, it produces "leet01" and "l337", shouldn't it also include "l33701"?

**Comment by Jul10l1r4** [comment]
This issue should be talking about this other project https://github.com/Jul10l1r4/gomutation
